Vagrant.configure("2") do |config|

    config.vm.box = "peru/ubuntu-20.04-server-amd64"
    config.vm.network :forwarded_port, guest: 80, host: 8080
    config.vm.synced_folder ".", "/home/vagrant/host"
       
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "moodle"
      vbox.memory = "4096"
      vbox.cpus = 2
    end
  
    config.vm.provision "shell", inline: <<-SHELL
      apt -y update
      
      # Install mariadb
      apt install -y mariadb-server mariadb-client
      mysql -uroot -e"CREATE DATABASE moodle;grant all privileges on moodle.* to 'moodle'@'localhost' IDENTIFIED BY 'password';flush privileges;"

      
      # Install apache
      apt install -y apache2

      # Install moodle
      apt install -y curl aspell clamav ghostscript graphviz php php-common libapache2-mod-php php-cli php-fpm php-mysql php-json php-opcache php-gmp php-curl php-intl php-mbstring php-xmlrpc php-gd php-xml php-zip php-soap

      if ! test -f "/var/www/html/index.php"; then
        curl -sS https://download.moodle.org/download.php/direct/stable311/moodle-latest-311.tgz | tar zx -C /var/www/html/ --strip-components=1
        chown -R www-data: /var/www/html
        mkdir /var/www/moodledata
        chown www-data: /var/www/moodledata/
        rm -f /var/www/html/index.html
        systemctl restart apache2 # php gd not installed
      fi

    SHELL
    
end
