Vagrant.configure("2") do |config|

    config.vm.box = "peru/ubuntu-20.04-server-amd64"
    config.vm.network :forwarded_port, guest: 80, host: 8080
       
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "wordpress"
      vbox.memory = "4096"
      vbox.cpus = 2
    end
  
    config.vm.provision "shell", inline: <<-SHELL

      # Password
      PASSWORD="password"

      apt-get -y update
      
      # Install mariadb
      apt-get install -y mariadb-server mariadb-client
      mysql -uroot -e"CREATE DATABASE wordpress;grant all privileges on wordpress.* to 'wordpress'@'localhost' IDENTIFIED BY '$PASSWORD';flush privileges;"

      
      # Install apache
      apt-get install -y apache2

      # Wordpress
      apt-get -y install apache2 curl ghostscript libapache2-mod-php mariadb-client php php-bcmath php-curl \
            php-imagick php-intl php-json php-mbstring php-mysql php-xml php-zip

      if ! test -f "/var/www/html/index.php"; then
        curl -sS https://wordpress.org/latest.tar.gz | sudo tar zx -C /var/www/html/ --strip-components=1
        chown -R www-data: /var/www/html
        rm -f /var/www/html/index.html
      fi

    SHELL
    
end
