Vagrant.configure("2") do |config|

    config.vm.box = "peru/ubuntu-20.04-server-amd64"
       
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "wp_db"
      vbox.memory = "2048"
      vbox.cpus = 1
    end
  
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt -y update
      
      # Install mariadb
      sudo apt install -y mariadb-server mariadb-client
      sudo mysql -uroot -e"CREATE DATABASE joomla;grant all privileges on joomla.* to 'joomla'@'localhost' IDENTIFIED BY 'password';flush privileges;"

    SHELL
    
end
