  Vagrant.configure("2") do |config|

  config.vm.box = "peru/ubuntu-20.04-server-amd64"
  config.vm.network :forwarded_port, guest: 8080, host: 8080
     
  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "alfresco"
    vbox.memory = "12288"
    vbox.cpus = Etc.nprocessors
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y docker-compose
    sudo usermod -aG docker vagrant
  SHELL
  
end
  