Vagrant.configure("2") do |config|

    config.vm.box = "peru/ubuntu-20.04-server-amd64"

    config.vm.define "g1" do |g1|
      g1.vm.network :private_network, ip: "192.168.0.1", virtualbox__intnet: true
      g1.vm.provider "virtualbox" do |vbox|
        vbox.name = "g1"
        vbox.memory = "2048"
        vbox.cpus = 1
      end
    end
    
    config.vm.define "g2" do |g2|
      g2.vm.network :private_network, ip: "192.168.0.2", virtualbox__intnet: true
      g2.vm.provider "virtualbox" do |vbox|
        vbox.name = "g2"
        vbox.memory = "2048"
        vbox.cpus = 1
      end
    end
    
    config.vm.define "g3" do |g3|
      g3.vm.network :private_network, ip: "192.168.0.3", virtualbox__intnet: true
      g3.vm.provider "virtualbox" do |vbox|
        vbox.name = "g3"
        vbox.memory = "2048"
        vbox.cpus = 1
      end
    end
    
end