Vagrant.configure("2") do |config|

    config.vm.box = "peru/ubuntu-20.04-server-amd64"

    (1..3).each do |i|

      config.vm.define "g#{i}" do |web|

        web.vm.hostname = "g#{i}"
        web.vm.network :private_network, ip: "192.168.0.1#{i}", virtualbox__intnet: true
        
        web.vm.provider "virtualbox" do |vbox|
          vbox.name = "g#{i}"
          vbox.linked_clone = true
          vbox.memory = "2048"
          vbox.cpus = 1
        end

        web.vm.provision "shell", inline: <<-SHELL
          apt -y update
          apt install -y software-properties-common
          add-apt-repository ppa:gluster/glusterfs-7
          apt install -y glusterfs-server
          systemctl start glusterd.service
          systemctl enable glusterd.service
       
        SHELL
      
      end
    
    end
end