Vagrant.configure("2") do |config|

    config.vm.box = "peru/ubuntu-20.04-server-amd64"
    config.vm.network :forwarded_port, guest: 8080, host: 8080
       
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "joomla"
      vbox.memory = "4096"
      vbox.cpus = 2
    end
  
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt -y update
      
      # Install mariadb
      sudo apt install -y mariadb-server mariadb-client
      
      # Install apache
      sudo apt install -y apache2
      sudo sed -i 's/:80>/:8080>/' /etc/apache2/sites-enabled/000-default.conf
      sudo sed -i 's/Listen 80/Listen 8080/'  /etc/apache2/ports.conf
      sudo systemctl restart apache2

      # Install Joomla
      sudo apt install -y php php-common libapache2-mod-php php-cli php-fpm php-mysql php-json php-opcache php-gmp php-curl php-intl php-mbstring php-xmlrpc php-gd php-xml php-zip unzip
      wget https://downloads.joomla.org/cms/joomla4/4-1-0/Joomla_4-1-0-Stable-Full_Package.zip
      sudo unzip Joomla_4-1-0-Stable-Full_Package.zip -d /var/www/html/
      sudo chown -R www-data: /var/www/html
      rm /var/www/html/index.html

    SHELL
    
end
